catalog/urls.py
from django.urls import path

from catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.index, name='index'),
    path(
        'product/<int:product_id>/',
        views.product_detail,
        name='product_detail'
    ),
    path(
        'category/<slug:category_slug>/',
        views.category_products,
        name='category_products'
    ),
    path('catalog/', views.catalog, name='catalog'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView

from users.forms import UserRegistrationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserRegistrationForm,
            success_url=reverse_lazy('catalog:index'),
        ),
        name='registration',
    ),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path(
        'add_to_shopping_cart/<int:product_id>/',
        views.add_to_shopping_cart,
        name='add_to_shopping_cart'
    ),
    path(
        'shopping_cart/<int:user_id>/',
        views.shopping_cart,
        name='shopping_cart'
    ),
    path(
        'remove_from_shopping_cart/<int:product_id>/',
        views.remove_from_shopping_cart,
        name='remove_from_shopping_cart'
    )
]

catalog/models.py
from django.core.validators import MinValueValidator
from django.db import models


class Category(models.Model):
    """Модель с категориями"""

    title = models.CharField(max_length=256, verbose_name='Название')
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text=(
            'Идентификатор страницы для URL;'
            ' разрешены символы латиницы, цифры, дефис и подчёркивание.'
        )
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')
    description = models.TextField('Описание')
    image = models.ImageField(
        'Фото',
        upload_to='product_images',
        blank=True,
        null=True
    )
    price = models.DecimalField(
        'Цена',
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0)]
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='Категория',
    )

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        default_related_name = 'products'
        ordering = ('id',)

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import Product


class User(AbstractUser):
    """Модель пользователя."""


class ShoppingCart(models.Model):
    """Модель корзины."""

    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        related_name='cart_items',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name="Товар",
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['user']
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'
        default_related_name = 'shopping_carts'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'product'], name='unique_shopping_cart'
            ),
        ]

    def __str__(self):
        return f'{self.user} - {self.product}'

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    """Форма регистрации пользователя"""

    class Meta(UserCreationForm.Meta):
        model = User

catalog/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

from catalog.models import Category, Product
from users.views import get_cart_products


def index(request):
    """Главная страница"""
    products = Product.objects.all()
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'cart_products': get_cart_products(request)
        }
    return render(request, 'catalog/index.html', context)


def catalog(request):
    """Страница с каталогом товаров"""
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'catalog/catalog.html', context)


def category_products(request, category_slug):
    """Страница с товарами определенной категории"""
    category = Category.objects.get(slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {
        'products': products,
        'category_title': category.title,
        'cart_products': get_cart_products(request)
    }
    return render(request, 'catalog/category_products.html', context)


def product_detail(request, product_id):
    """Страница с информацией о товаре"""
    product = get_object_or_404(Product, id=product_id)
    context = {
        'product': product,
    }
    return render(request, 'catalog/product_detail.html', context)

users/views.py
from django.shortcuts import get_object_or_404, redirect, render

from catalog.models import Product
from users.models import ShoppingCart


def profile(request):
    """Личный кабинет пользователя."""
    user = request.user
    if user.is_authenticated:
        context = {"user": user}
        return render(request, 'users/profile.html', context)
    return redirect('login')


def add_to_shopping_cart(request, product_id):
    """Добавить товар в корзину."""
    user = request.user
    if user.is_authenticated:
        product = get_object_or_404(Product, id=product_id)
        ShoppingCart.objects.get_or_create(user=user, product=product)
        return redirect(request.META.get('HTTP_REFERER', '/'))
    return redirect('login')


def remove_from_shopping_cart(request, product_id):
    """Удалить товар из корзины."""
    user = request.user
    if not user.is_authenticated:
        return redirect('login')
    cart_item = ShoppingCart.objects.filter(
        user=user,
        product=product_id
    )
    if cart_item.exists():
        cart_item.delete()
    return redirect(request.META.get('HTTP_REFERER', '/'))


def get_cart_products(request):
    """Функция для получения товаров в корзине."""
    if request.user.is_authenticated:
        return set(
            ShoppingCart.objects.filter(
                user=request.user
            ).values_list('product_id', flat=True)
        )
    return set()


def shopping_cart(request, user_id):
    """Корзина."""
    user = request.user
    products = Product.objects.filter(shopping_carts__user=user_id)
    context = {
        "products": products,
        "user": user,
        "cart_products": get_cart_products(request),
    }
    return render(request, 'users/shopping_cart.html', context)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
        {% block content %}{% endblock %}
    </main>
  </body>
</html>

templates/catalog/catalog.html
{% extends "base.html" %}
{% block title %}
    Каталог
{% endblock %}
{% block content %}
    {% for category in categories %}
    <article class="mt-4">
        <a href="{% url 'catalog:category_products' category.slug %}" style="text-decoration:None; color:black">
            <div class="container card border border-warning" style="text-align:center; width: 30rem;">
                <h4>{{ category.title }}</h4>
            </div>
        </a>
    </article>
    {% endfor %}
{% endblock %}

templates/catalog/category_products.html
{% extends "base.html" %}
{% block title %}
    Товары в категории {{ category_title }}
{% endblock %}
{% block content %}
    <h2 class="mt-3" style="margin-left:20px;">Товары в категории {{ category_title }}:</h2>
    {% for product in products %}
    <article class="mt-4" style="float:left; margin-left:20px">
        {% include "includes/product_card.html" %}
    </article>
    {% endfor %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
    Главная
{% endblock %}
{% block content %}
    <h2 class="mt-3" style="margin-left:20px;">Новинки:</h2>
    {% for product in page_obj %}
    <article class="mt-4" style="float:left; margin-left:20px">
        {% include "includes/product_card.html" %}
    </article>
    {% endfor %}
    <div style="clear: both; padding-top: 3px; margin: 0 auto; width: fit-content;">
        {% include "includes/paginator.html" %}
    </div>
{% endblock %}

templates/catalog/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ product.title }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card mt-5 border border-warning" style="width: 40rem;">
      <div class="card-body">
        {% if product.image %}
          <a href="{{ product.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ product.image.url }}">
          </a>
          {% else %}
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/placeholder.jpg' %}" width="400">
        {% endif %}
        <h5 class="card-title">{{ product.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
            <small style="color:#f2c830;">
                {{ product.price }} Руб.
            </small>
        </h6>
        <p class="card-text">{{ product.description|linebreaksbr }}</p>
      </div>
    </div>
  </div>
{% endblock %}

templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
    <nav class="navbar" style="background-color: #f2c830;">
        <div class="container">
            <a class="navbar-brand" href="{% url 'catalog:index' %}">
                Главная
            </a>
            <a class="nav-link {% if view_name == 'catalog:catalog' %} text-white {% endif %}" href="{% url 'catalog:catalog' %}">
                Каталог
            </a>
            {% if user.is_authenticated %}
                <a class="nav-link {% if view_name == 'users:profile' %} text-white {% endif %}" href="{% url 'users:profile' %}">
                    Профиль
                </a>
            {% else %}
                <a class="nav-link{% if view_name == 'login' %} text-white {% endif %}" href="{% url 'login' %}">
                    Войти
                </a>
                <a class="nav-link{% if view_name == 'registration' %} text-white {% endif %}" href="{% url 'registration' %}">
                    Регистрация
                </a>       
          {% endif %}

        </div>
    </nav>
</header>
{% endwith %}

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page=1" style="color:#f2c830;">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" style="color:#f2c830;">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
        <li class="page-item active" style="background-color: transparent; border: none;">
            <span class="page-link" style="color: #f2c830; background-color: #333; border-color: #f2c830;">{{ i }}</span>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}" style="color: #f2c830;">{{ i }}</a>
        </li>
    {% endif %}
{% endfor %}


      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="color:#f2c830;">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" style="color:#f2c830;">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/product_card.html
{% load static %}
<div class="col d-flex justify-content-center">
  <div class="card border border-warning" style="width: 30rem;">
    <div class="card-body">
      {% if product.image %}
        <a href="{{ product.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ product.image.url }}" width="180">
        </a>
      {% else %}
        <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/placeholder.jpg' %}" width="180">
      {% endif %}
      <h5 class="card-title">{{ product.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small style="color:#f2c830;">
          {{ product.price }} Руб.
        </small>
      </h6>
      <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-warning">Посмотеть товар</a>
      {% if product.id in cart_products %}
        <a href="{% url 'users:remove_from_shopping_cart' product.id %}" class="btn btn-danger">Убрать из корзины</a>
      {% else %}
        <a href="{% url 'users:add_to_shopping_cart' product.id %}" class="btn btn-warning">В корзину</a>
      {% endif %}
    </div>
  </div>
</div>

templates/users/profile.html
{% extends "base.html" %}
{% block title %}
    Профиль
{% endblock %}
{% block content %}
    <h1 style="text-align:center;" class="mt-5">Профиль пользователя <p style="color:#f2c830;">{{ user.username }} </p></h1>
    <small>
        <ul class="list-group list-group-horizontal justify-content-center mb-3">
          <li class="list-group-item text-muted">Имя пользователя: {% if user.get_full_name %}{{ user.get_full_name }}{% else %}не указано{% endif %}</li>
          <li class="list-group-item text-muted">Регистрация: {{ user.date_joined }}</li>
        </ul>
    </small>
    <article class="mt-4">
        <a href="{% url 'users:shopping_cart' user.id %}" style="text-decoration:None; color:black">
            <div class="container card border border-warning" style="text-align:center; width: 30rem;">
                <h4>Корзина</h4>
            </div>
        </a>
    </article>
    <article class="mt-4">
        <a href="{% url 'password_change' %}" style="text-decoration:None; color:black;">
            <div class="container card border border-warning" style="text-align:center; width: 30rem;">
                <h4>Сменить пароль</h4>
            </div>
        </a>
    </article>
    <article class="mt-4">
        <a href="{% url 'logout' %}" style="text-decoration:None; color:black;">
            <div class="container card border border-warning" style="text-align:center; width: 30rem;">
                <h4>Выйти из аккаунта</h4>
            </div>
        </a>
    </article>
{% endblock %}

templates/users/shopping_cart.html
{% extends "base.html" %}
{% block title %}
    корзина
{% endblock %}
{% block content %}
    <h2 class="mt-3" style="margin-left:20px;">корзина пользователя {{ user.username }}:</h2>
    <div class="cart-container" style="display: flex; flex-direction: column; align-items: center;">
        {% for product in products %}
            <article class="mt-2 mb-2">
                {% include "includes/product_card.html" %}
            </article>
        {% endfor %}
    </div>
{% endblock %}